#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

home:
    path: /home
    controller: App\Controller\HomeController::index

profile:
    path: /profile
    controller: App\Controller\ProfileController::index

groups:
    path: /groups
    controller: App\Controller\GroupsController::index

create_group:
    path: /create_groupe
    controller: App\Controller\CreateGroupController::index