#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

home:
    path: /
    controller: App\Controller\HomeController::index

profile:
    path: /profile
    controller: App\Controller\ProfileController::index

profile_guest:
    path: /profile/{id}
    controller: App\Controller\ProfileController::showProfile

groups:
    path: /groups
    controller: App\Controller\GroupsController::index

create_group:
    path: /create_groupe
    controller: App\Controller\CreateGroupController::index

api_media:
    path: /api_media/{id}
    controller: App\Controller\ApiMediaController::index